<template>
  <section>
    <v-container fluid>
      <v-row justify="center">
        <v-col cols="12" sm="8">
          <h2 class="text-center">
            Vi kan hjælpe dig med
            <br />digital transformation på to fronter
          </h2>
        </v-col>
      </v-row>
      <v-row justify="center">
        <v-col cols="10">
          <v-row justify="space-around">
            <v-col cols="12" md="4">
              <div class="text-center d-block">
                <v-row justify="center">
                  <v-col cols="6" md="8">
                    <img src="/illustration1.svg" alt="graf" />
                  </v-col>
                </v-row>
                <h3 class="pb-6">
                  Strategisk rådgivning om digital transformation
                </h3>
                <p>
                  Udnytter din virksomhed sit digitale potentiale? Hvilke
                  forretningsmuligheder er der, og hvad betyder det på et
                  strategisk plan?
                </p>
              </div>
            </v-col>
            <v-col cols="12" md="4">
              <div class="text-center d-block">
                <v-row justify="center">
                  <v-col cols="6" md="8">
                    <img src="/illustration2.svg" alt="kurve" />
                  </v-col>
                </v-row>
                <h3 class="pb-6">Eksekvering af digital transformation</h3>
                <p>
                  I ved, hvad I vil, men I har brug for hjælp til at rulle
                  strategien ud i forhold til organisationen og det digitale
                  fundament bl.a. på Sitecore. Det handler om mennesker og
                  resultater.
                </p>
              </div>
            </v-col>
          </v-row>
        </v-col>
      </v-row>
    </v-container>
  </section>
</template>

<style lang="scss" scoped>
section {
  background-color: white;
  color: black;
  padding: 75px 0 50px 0;
}
</style>
